const books = [
  {
    id: 1,
    category: 'Action',
    title: 'The Hunger Games',
    author: 'Suzanne Collins',
    readProgress: 64,
  },
  {
    id: 2,
    category: 'Science Fiction',
    title: 'Dune',
    author: 'Frank Herbert',
    readProgress: 50,
  },
  {
    id: 3,
    category: 'Economy',
    title: 'Capital in the Twenty-First Century',
    author: 'Suzanne Collins',
    readProgress: 24,
  },
];

export const categories = [
  { name: 'Fiction' },
  { name: 'Non-fiction' },
  { name: 'Mystery' },
  { name: 'Thriller' },
  { name: 'Science Fiction' },
  { name: 'Fantasy' },
  { name: 'Romance' },
  { name: 'Historical Fiction' },
  { name: 'Horror' },
  { name: 'Adventure' },
  { name: 'Biography' },
  { name: 'Autobiography' },
  { name: 'Poetry' },
  { name: 'Drama' },
  { name: 'Comedy' },
  { name: 'Satire' },
  { name: 'Crime' },
  { name: 'Young Adult' },
  { name: "Children's" },
  { name: 'Self-help' },
  { name: 'Travel' },
  { name: 'Science' },
  { name: 'Philosophy' },
  { name: 'Religion' },
  { name: 'Art' },
  { name: 'Business' },
  { name: 'Psychology' },
  { name: 'Health and Wellness' },
  { name: 'Cookbooks' },
  { name: 'Sports' },
];
export default books;
